Add Missing Browser Exception.
testproject-io/java-sdk pull request #51
Opened 2020-11-26 09:16 UTC by DavidG8168

Added new custom exception for when the requested browser is not found on the current machine.

2020-11-26 14:29 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            case HttpURLConnection.HTTP_NOT_FOUND:
What happens when a device requested is not connected? 
If it's a 404 response as well, perhaps we have to adda new class for `DeviceNotConnectedException` as well, and distinguish here between a mobile and a web session.

2020-11-26 16:17 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            case HttpURLConnection.HTTP_NOT_FOUND:
@mstrelex Same happens, added another exception for mobile devices. 
Selected the correct exception based on the response message returned by the agent. 

This might need to go into the Python SDK as well.

2020-11-30 14:04 UTC, mstrelex requested changes

2020-11-30 14:04 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            throw new AgentConnectException("Requested browser is not installed on the machine", e);
```suggestion
            throw new AgentConnectException("Requested browser is not installed", e);
```

2020-11-30 14:04 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            throw new AgentConnectException("Requested browser is not installed on the machine", e);
Add Browser name.

2020-11-30 14:04 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            throw new AgentConnectException("Requested device was not found", e);
Add device UDID

2020-11-30 14:04 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/exceptions/MissingBrowserException.java
> +        this("Requested browser not installed on machine");
```suggestion
        this("Requested browser not installed");
```

2020-11-30 14:49 UTC, mstrelex commented
@DavidG8168 Please fix the DCO (sign-off) error as well.

2020-11-30 18:36 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            throw new AgentConnectException("Requested browser is not installed on the machine", e);
@mstrelex Changed.

2020-11-30 18:36 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            throw new AgentConnectException("Requested browser is not installed on the machine", e);
Added.

2020-11-30 18:36 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +            throw new AgentConnectException("Requested device was not found", e);
Also added.

2020-11-30 18:36 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/exceptions/MissingBrowserException.java
> +        this("Requested browser not installed on machine");
Removed.

2020-12-02 14:34 UTC, mstrelex requested changes

2020-12-02 15:35 UTC, mstrelex commented
@DavidG8168 DCO

2020-12-02 16:09 UTC, DavidG8168 commented
@mstrelex Message syntax changed, rebased and DCO.

2020-12-03 17:28 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/exceptions/MissingBrowserException.java
> +        this("Requested browser not installed");
```suggestion
        this("Requested browser is not installed");
```

2020-12-03 17:29 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +        final String deviceNotFoundMessage = "Requested device was not found";
```suggestion
        final String deviceNotFoundMessage = "Requested device is not connected";
```

2020-12-03 17:29 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +                    LOG.error("Failed to initialize a session with the Agent - Requested device is not connected");
```suggestion
                    LOG.error("Failed to initialize a session with the Agent - requested device is not connected");
```

2020-12-03 17:31 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +        final String deviceNotFoundMessage = "Requested device was not found";
Instead of inspecting Agent's reply text, perhaps it's better to determine the session type - Web or Mobile using the provided capabilities such as if `browserName` is provided -> Web, otherwise Mobile.

2020-12-07 08:23 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +        final String deviceNotFoundMessage = "Requested device was not found";
@mstrelex Using the capabilities now.

2020-12-07 16:28 UTC, mstrelex approved these changes

2020-12-07 16:28 UTC, merged