Test name is not reported when driver.quit() isn't called after test execution
testproject-io/java-sdk pull request #70
Opened 2021-01-13 17:28 UTC by DavidG8168

2021-01-14 14:37 UTC, mstrelex requested changes

2021-01-14 14:37 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +    public void remoteShutdownThread(final int priority) {
Remote?

2021-01-14 14:37 UTC, mstrelex commented
@vitalybu Please have a look

2021-01-14 14:42 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +    public void remoteShutdownThread(final int priority) {
Typo, fixed.

2021-01-15 12:35 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/helpers/DriverShutdownThread.java
> +public class DriverShutdownThread {
This class kinda feels unnecessary now.
Each driver instance should simply register a lambda function with the `ShutdownThreadManager` and close itself...
Maybe use the self object hash as a key to support unregistering.

2021-01-15 12:35 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +public final class ShutdownThreadManager extends Thread {
I don't really think we need a numeric priority here, as we only have two so called "priorities".
We want to make sure that all the drivers close before shutting down the `AgentClient`.
So maybe it's better to have a simple list of drivers and an instance of the `AgentClient`.
Then we can simply close the drivers first without any arbitrary number priorities.

2021-01-15 12:35 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +    private final Runnable shutdownThread;
This can removed (as it's a simply lambda: `() -> close(true);`)

2021-01-15 14:39 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/helpers/DriverShutdownThread.java
> +public class DriverShutdownThread {
Removed it, everything is done now through the manager.
Drivers threads are registered with their hash.

2021-01-15 14:40 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +public final class ShutdownThreadManager extends Thread {
Drivers have been separated from the client, client will be stored separately.
After the drivers are shutdown, the client will be shutdown.

2021-01-15 14:40 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +    private final Runnable shutdownThread;
Removed.

2021-01-15 15:27 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +    public void addClientShutdownThread(final Runnable shutdownThread) {
The class is called `ShutdownThreadManager`, so no reason adding `...ShutdownThread()` to all the methods.

```suggestion
    public void addAgentClient(final Runnable shutdownThread) {
```

2021-01-15 15:27 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +    public void removeClientShutdownThread() {
```suggestion
    public void removeAgentClient() {
```

2021-01-15 15:27 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +    }
By passing an `Object`, you can make the calling code more readable, as it'll look like:
```java
X.addDriver(this, this::stop);
```
Instead of:
```java
X.addDriver(this.hashCode(), this::stop);
```

The ShutdownManager is the one which decided to use `hashCode()` now, but in the future it may decide to use a different key...

```suggestion
    public void addDriver(final Object driver, final Runnable shutdownMethod) {
        driverShutdownThreads.put(driver.hashCode(), shutdownMethod);
    }
```

2021-01-15 16:25 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +    public void addClientShutdownThread(final Runnable shutdownThread) {
Makes sense, addressed.

2021-01-15 16:25 UTC, DavidG8168 commented on src/main/java/io/testproject/sdk/internal/helpers/ShutdownThreadManager.java
> +    }
Changed.

2021-01-15 18:26 UTC, vitalybu approved these changes

2021-01-16 17:29 UTC, merged